### ISSUE TITLE
Processor processes failed extrinsics

### ISSUE THREAD

**Issue by bedeho** [Joystream/hydra#134]
Events from failed extrinsics, and I guess also failed extrinsics once we had extrinsic mappings, are handled by mappings despite the best practice that failed extrinsics should not have any storage side effects.

Is this a good policy? Should we allow developer to control this?

Right now we actually _need this_, perversely, because one of our broken extrinsics break this policy.

**Comment by dzhelezov** [comment]
- For events: that's correct, we fetch the events in the `ApplyExtrinsic` phase and it turns out that the events may be emitted even in the case the extrinsic has failed. Ideally, this setting should be optional, with the default behavior that only events emitted by successful extrinsics are processed.

- For extrinsics: In the [Virtual events design](https://github.com/Joystream/hydra/pull/125/commits/053b8bdc6a38d1c95eebfc2b4ea0f96bb20df585#diff-834d4931401c1060d70a1d8777db1b58ab6d02271c29012f3b1b1a331aec6b87) the idea is to process extrinsics at the time the corresponding `ExtrinsicSuccess` is emitted. Thus, only successful extrinsics are going to be processed. However, batch calls do emit `ExtrinsicSuccess` even if some of the sub-calls failed, so this indeed requires additional logic anyway.

**Comment by dzhelezov** [comment]
As an afterthought: I think it's a good addition for the indexer to include in the event data more context about the extrinsic that has emitted the event. It then should be fairly trivial for the processor to filter them off.

**Comment by bedeho** [comment]
> Thus, only successful extrinsics are going to be processed

`ExtrinsicSuccess` is not a required indication when there are side-effects to the system. The non-atomic batching extrinsic is one example, I am sure there are others. In these cases, any well constructed extrinsic will at least encode information in its failure value about what side-effects there were, or emit a specific failure event that carries this information. Mappings need to be able to process at least one of these in order to keep up properly, ideally we can support both, because sometimes a module developer will not take proper care to offer at least one of these.

**Comment by dzhelezov** [comment]
@bedeho It is possible to specify `triggerEvents` for extrinsic mappings in Hydra v3: https://dzhelezov.gitbook.io/hydra/docs/mappings/mapping-types
