### ISSUE TITLE
Pre mappings

### ISSUE THREAD

**Issue by metmirr** [Joystream/hydra#59]
Currently, inside the mappings, we do a lot of decoding to get data from the events and extrinsics. In last Hydra meeting, we decided to have pre mappings to do data decoding.

The mapping author will need to define:
1. The type that will be returned by pre handler
2. Pre handler function that takes `Substrate` event and return the type defined in step 1
3. The actual mapping which takes a `DB` instance and the type defined in step 1

Let's look at an example for Joystream's `MemberRegistered` event handler:

```ts
// Type defination
export interface JoystreamMember extends BaseEventHandlerParameter {
	memberId: BN;
	handle: string;
	avatarUri: string;
	about: string;
	registeredAtBlock: number;
	rootAccount: Buffer;
	controllerAccount: Buffer;
}


// Pre mapping
function pre_members_MemberRegistered(event: SubstrateEvent): JoystreamMember {
	const { 0: memberId, 1: accountId } = event.params;

	debug(`Substrate event: ${JSON.stringify(event)}`);
	assert(event.extrinsic, "No extrinsic data");

	const extrinsicArgs = event.extrinsic.args.map((arg) => arg.value.toString());

	return {
		registeredAtBlock: event.blockNumber,
		memberId: new BN(memberId.value.toString()),
		rootAccount: Buffer.from(accountId.value.toString()),
		controllerAccount: Buffer.from(accountId.value.toString()),
		handle: extrinsicArgs[1],
		avatarUri: extrinsicArgs[2],
		about: extrinsicArgs[3],
	};
}

// Actual mapping
export async function members_MemberRegistered(db: DB, member: JoystreamMember) {
	let m = new Member({ ...member });
	db.save<Member>(m);
}
```

**Comment by dzhelezov** [comment]
Looks great! A few comments: 
- I think it would be beneficial to put in a backward-compatible way (e.g. no changes will be needed for the processor). In the example above it may look like  
```
export async function members_MemberRegistered(db: DB, event: SubstrateEvent): Promise<void> {
    const joystreamMember = pre_members_MemberRegistered(event);
    await  _members_MemberRegistered(db, joystreamMember);
}

export async function _members_MemberRegistered(db: DB, member: JoystreamMember) {
  let m = new Member({ ...member });
  // await is necessary here btw, so we need to use linters in order to catch such errors!
  await db.save<Member>(m);
}
```

- A general thought: we should try to make pre-mappers as standard and dumb as possible in order to simplify auto-generating in the future. So perhaps to make it uniform the extrinsic args may be unboxed in a similar way: 
```
const { 0: handle, 1: avatarUri, 2: about } = event.extrinsic.args
```
and then values are taken similarly.

- Another small comment: perhaps a cleaner and more general way is to have type conversion (e.g. `memberId.value as string` vs `member.value.toString()`). The benefit is two-fold: first, `toString()` is an overloaded method which may or may not give the correct deserialisation, and it may be undefined at all. Second, one can easily write `memberId.value as { id: string; profile: string }` should we expect a more complex value. If for some reason the value does not conform to the expected interface, the runtime error will clearly point it out, while in the example above we may end up saving some garbage into the database.

**Comment by metmirr** [comment]
Thanks!

- It makes sense and will not require any changes on MappingProcessor side.
- For pre-mappings I planned the same approach like `processingPack` so I needed a class/interface for the return types and function paramater.  `BaseEventHandlerParameter` is a class has no member, only for type purposes `class BaseEventHandlerParameter { }`
- Okay I will follow that for all the pre-mappings
- Def will have a huge benefit especially for the runtime struct types which we expect to have

**Comment by bedeho** [comment]
Great work guys, this looks like the right direction for sure.
