### ISSUE TITLE
Abstract mappings

### ISSUE THREAD

**Issue by bedeho** [Joystream/hydra#61]
# Background

Currently, the only way to trigger a mapper is in response to an event. We already have plans to extend this to also cover transactions, and moveover, we have plans to have mappers with static signatures. This is an excellent start, but these solutions are temporary solutions to the more general issue that the level of abstractions desired for mappers to key off can be totally arbitrary, and unrelated to blockchain level concepts. The most salient examples are the following modules

- `EVM`: https://substrate.dev/docs/en/knowledgebase/runtime/frame#evm
- `Contract`: https://substrate.dev/docs/en/knowledgebase/runtime/frame#contracts

These are used in plenty of chains, such as Acala, Edgewere, Moonbeam, and in the future also Joystream.

In these cases, the mapping author wants to key off type safe smart contract initiations, which do not exist as concepts in the native Runtime metadata. It would be unworkable to require the mapping author to decode this by hand, as they would have to understand implementation details of the modules above, and it would be hard to reuse cleanly across mappings for different chains or even different input schemas for a single chain.

# Proposal

Hydra should allow some user provided middleware code to run during the generation step, and this code can understand whatever specific abstraction the mapping author was targeting. Then there should be standardized middle ware, like `hydera-evm` or `hydra-contract` that authors could take off the shelf, and then write mappings and manifest files cleanly.

**Comment by dzhelezov** [comment]
One random thought in this direction. 

Could it be the case the amount of work and efforts to generalize and cover possible scenarios for the mappers will fall short as the learning curve on how to write a mapper becomes steeper due to an increasing level of abstraction? What I mean here is that perhaps at some point having only the indexer endpoint + some ad-hoc templates/tooling would be _good enough_ for most of the developers. A GraphQL interface with extensive filtering will look familiar, and they may or may not be willing to process the events in the way dictated by the mappers. Assuming that the developers will run a processor in-house or self-hosted in the cloud, I can foresee a lot of requests for additional support, starting from some mild variations of the DB backend ending with some completely different pipeline architectures. Indeed the way we do mappings is probably already not the most efficient one.

The way mappings are structured at the moment already places the developers in a rather stiff position with a very limited number of options. This is probably good for the Babylon/Joystream use-case but not sure how it plays out if the ecosystem grows.

**Comment by bedeho** [comment]
I did not understand this reply, so lets table it for next Hydra team call, it's not urgent after all.
